### PR TITLE
Add install options for Caffe2 builds and tests

### PR DESCRIPTION
**Pull request by orionr**
This adds vision (OpenCV and ffmpeg), DB (LMDB, LevelDB, and Redis), protobuf, and Android as new docker installable components.

This is a part of getting Caffe2 tests to run on PyTorch docker images and CircleCI as being worked on in https://github.com/pytorch/pytorch/pull/13733 

cc @yf225 @pjh5

### CODE REVIEW

**Comment by orionr** [comment]
@yf225 after this lands do I need to then make changes to oss-ci to set these or is editing `.circleci/config.yml` going to be the next step?

**Comment by yf225** [comment]
Thanks @orionr! I think the first step would be to update the version number in https://github.com/pytorch/ossci-job-dsl/blob/master/src/main/groovy/ossci/pytorch/DockerVersion.groovy, and then we can open a PR in PyTorch repo to test the new images against master.

**Comment by orionr** [comment]
Also, @yf225, do we have CentOS and ROCm docker images for PyTorch? If not, I might want to add those as well so we eventually can move everything over.

**Comment by orionr** [comment]
One more question - where do I get the new version number from? :)

**Pull request merged**
